on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pack
        uses: buildpacks/github-actions/setup-pack@v5.0.0

      - name: Publish container
        run: pack build --builder=paketobuildpacks/builder:base --publish ghcr.io/${{ github.actor }}/random-num
